language: csharp
solution: Jump.Location.sln
install:
  - sudo apt-get install -y powershell
  - nuget restore Jump.Location.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Jump.Location.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./Jump.Location.Specs/bin/Release/Jump.Location.Specs.dll
